# Generated by Django 3.1.2 on 2020-12-18 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20201216_1034'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='students',
            table='student',
        ),
    ]
