# Generated by Django 3.1.2 on 2020-12-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20201218_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='about',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
