# Generated by Django 3.1.2 on 2020-12-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20201218_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='schools',
            name='schoolLogo',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
