# Generated by Django 3.1.2 on 2020-12-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_schools_schoollogo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='name',
        ),
        migrations.AddField(
            model_name='students',
            name='firstname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='lastname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
